### ISSUE TITLE
Logging in twice or more with the same or different account shows the last page visited.

### ISSUE THREAD

**Issue by honeyanant** [rash805115/P.O.T.S#29]
1.Logged in with Google and suppose I am on developers page and then logged out.
2.Again when logged in with Facebook,the page it shows is still developers page.

Other Scenario
Logged in with Google, I am on wishlist page, logged off and again logged in with same account i.e, Google, it still shows the wishlist page.

**Comment by rash805115** [comment]
Its a feature, not a bug. The login redirects the user to the last page which was requested before login. 

Scenario 1: You were logged in with google and were on developers page. Then you log out. But the last page that you visited was the developers page. Hence when you login again, with any account, you will always land in developers page.

Why is this important?
Because lets say someone gave you a link for an app. e.g. yourpots.com/apps/test/21. But you were not logged in. So it will redirect from this link and will ask you to login. Once you login, system can take you either to the home page, or the last page you requested, i.e. the app page. We chose the latter option because its much more user friendly.

So as a general rule, we always redirect back to the "intended" page.
